@api = http://localhost:3000
# @api = https://webhookscrum.onrender.com

@token = "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"


### test
GET {{api}}/politica
Content-Type: application/json


### Login
POST {{api}}/chatbot
Content-Type: application/json
Authorization: Bearer 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

{
  "responseId": "d1b51e9d-8422-4e90-a6be-ffc6dad21d38-0fffcc35",
  "queryResult": {
    "queryText": "scrum: puedes ayudarme a definir un diagrama de secuencia?",
    "parameters": {
      "any": "puedes ayudarme a definir un diagrama de secuencia?"
    },
    "allRequiredParamsPresent": true,
    "outputContexts": [
      {
        "name": "projects/scrumbot-nnoi/agent/sessions/d7060b16-6274-0625-b0f8-8a557e851d65/contexts/__system_counters__",
        "parameters": {
          "no-input": 0,
          "no-match": 0,
          "any": "puedes ayudarme a definir un diagrama de secuencia?",
          "any.original": "puedes ayudarme a definir un diagrama de secuencia?"
        }
      }
    ],
    "intent": {
      "name": "projects/scrumbot-nnoi/agent/intents/1e81ff9c-8094-4613-b7e7-e31ee797a244",
      "displayName": "scrum"
    },
    "intentDetectionConfidence": 0.3262566,
    "languageCode": "es"
  },
  "originalDetectIntentRequest": {
    "source": "DIALOGFLOW_CONSOLE",
    "payload": {}
  },
  "session": "projects/scrumbot-nnoi/agent/sessions/d7060b16-6274-0625-b0f8-8a557e851d65"
}
