@api = http://localhost:3000
# @api = https://webhookscrum.onrender.com

@token = "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"


### test
GET {{api}}/politica
Content-Type: application/json


### Login
POST {{api}}/chatbot
Content-Type: application/json

{
  "responseId": "b8d78d8f-f9c3-4a76-9c52-6aa9c1630a1d-0fffcc35",
  "queryResult": {
    "queryText": "scrum: Me ayudas a elegir herramientas en la web para el manejo de la metodologia scrum?",
    "parameters": {
      "any": "Me ayudas a elegir herramientas en la web para el manejo de la metodologia scrum?"
    },
    "allRequiredParamsPresent": true,
    "outputContexts": [
      {
        "name": "projects/scrumbot-nnoi/agent/sessions/6badb514-8f89-4e3b-32ae-b50ba99059c9/contexts/__system_counters__",
        "parameters": {
          "no-input": 0,
          "no-match": 0,
          "any": "Me ayudas a elegir herramientas en la web para el manejo de la metodologia scrum?",
          "any.original": "Me ayudas a elegir herramientas en la web para el manejo de la metodologia scrum?"
        }
      }
    ],
    "intent": {
      "name": "projects/scrumbot-nnoi/agent/intents/1e81ff9c-8094-4613-b7e7-e31ee797a244",
      "displayName": "scrum"
    },
    "intentDetectionConfidence": 0.53980726,
    "languageCode": "es"
  },
  "originalDetectIntentRequest": {
    "source": "DIALOGFLOW_CONSOLE",
    "payload": {}
  },
  "session": "projects/scrumbot-nnoi/agent/sessions/6badb514-8f89-4e3b-32ae-b50ba99059c9"
}
